# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: build
build:
	npm run build

.PHONY: check
check:
	npm run check 

.PHONY: install
install:
	npm ci

.PHONY: lint
lint:
	npm run lint

.PHONY: unit-test
unit-test:
	npm test
